jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: node:14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Transfer files to local server
        run: |
          scp -r . root@192.168.18.34:/var/wwww/html
