name: Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and package
      run: |
        # Add commands to build and package your application
        # For example, npm install, build, etc.

    - name: Transfer files and execute scripts
      run: |
        scp -r . root@192.168.18.34:/var/www/html
        ssh root@192.168.18.34 'bash -s' < scripts/install_and_start_nginx.sh
